In [82]:
import pandas as pd
import re

In [83]:
pd.set_option('display.max_colwidth', None)

In [84]:
sin_nombre = pd.read_csv('../data/raw/sin_nombre_all.csv')

In [85]:
sin_nombre.shape

(397, 28)

In [86]:
trash_words = 'VACCINE PLATFORM|patent|regulatory elements|METHODS|Modified Microbial Nucleic Acid'

In [87]:
trash_mask = sin_nombre['GenBank_Title'].str.contains(trash_words, case=False, na=False, regex=True)

In [88]:
trash_rows = sin_nombre[trash_mask]

In [89]:
print(f'Broj pronađenih redova: {len(trash_rows)}')

Broj pronađenih redova: 31

In [90]:
display(trash_rows[['Accession', 'GenBank_Title','Segment']].head(10))

,Accession,GenBank_Title,Segment
15,PG340915.1,JP 2023515355-A/7: RAPID VACCINE PLATFORM,NaN
16,PG340916.1,JP 2023515355-A/8: RAPID VACCINE PLATFORM,NaN
17,PG340917.1,JP 2023515355-A/9: RAPID VACCINE PLATFORM,NaN
18,PG340918.1,JP 2023515355-A/10: RAPID VACCINE PLATFORM,NaN
19,PL092163.1,"KR 1020240003760-A/15: New regulatory elements for enhancing RNA stability or mRNA translation, ZCCHC2 interacting with the same, and use thereof",NaN
20,PL092227.1,"KR 1020240003760-A/79: New regulatory elements for enhancing RNA stability or mRNA translation, ZCCHC2 interacting with the same, and use thereof",NaN
21,PL092228.1,"KR 1020240003760-A/80: New regulatory elements for enhancing RNA stability or mRNA translation, ZCCHC2 interacting with the same, and use thereof",NaN
22,PL092350.1,"KR 1020240003761-A/15: A method of screening regulatory elements for enhancing mRNA translation, new regulatory elements according to the method, and use thereof",NaN
23,PL092414.1,"KR 1020240003761-A/79: A method of screening regulatory elements for enhancing mRNA translation, new regulatory elements according to the method, and use thereof",NaN
24,PL092415.1,"KR 1020240003761-A/80: A method of screening regulatory elements for enhancing mRNA translation, new regulatory elements according to the method, and use thereof",NaN

Uklanjanje patenata, dijagnostičkih metoda, vakcinacionih platformi i veštačkih modifikovanih sekvenci (KR/JP patenti, regulatorni elementi iRNK) kako bi se eliminisao šum i zadržali isključivo prirodni S, M i L segmenti hantavirusa.

In [91]:
sin_nombre = sin_nombre[
    ~sin_nombre['GenBank_Title'].str.contains(trash_words, case=False, na=False)].copy()

In [92]:
sin_nombre.shape

(366, 28)

In [93]:
sin_nombre['Segment'].value_counts(dropna=False)

Segment
NaN    138
M      124
S       63
L       41
Name: count, dtype: int64

In [94]:
display(sin_nombre[sin_nombre['Segment'].isna()][['Accession', 'GenBank_Title']].head(50))

,Accession,GenBank_Title
194,KX066110.1,"Orthohantavirus sinnombreense strain HV B0530012 nucleocapsid protein (N) gene, partial cds"
195,KX066111.1,"Orthohantavirus sinnombreense strain HV B0770007 nucleocapsid protein (N) gene, partial cds"
196,KX066112.1,"Orthohantavirus sinnombreense strain HV B0530013 nucleocapsid protein (N) gene, partial cds"
197,KX066113.1,"Orthohantavirus sinnombreense strain HV B0530015 nucleocapsid protein (N) gene, partial cds"
198,KX066114.1,"Orthohantavirus sinnombreense strain HV B0770009 nucleocapsid protein (N) gene, partial cds"
199,KX066117.1,"Orthohantavirus sinnombreense strain HV B0770021 nucleocapsid protein (N) gene, partial cds"
200,KX066118.1,"Orthohantavirus sinnombreense strain HV B0770014 nucleocapsid protein (N) gene, partial cds"
201,KX066119.1,"Orthohantavirus sinnombreense strain HV B0530001 nucleocapsid protein (N) gene, partial cds"
202,KX066120.1,"Orthohantavirus sinnombreense strain HV B0770015 nucleocapsid protein (N) gene, partial cds"
203,KX066121.1,"Orthohantavirus sinnombreense strain HV B0770016 nucleocapsid protein (N) gene, partial cds"
204,KX066122.1,"Orthohantavirus sinnombreense strain HV Q0020010 nucleocapsid protein (N) gene, partial cds"
250,DQ090888.1,"Blue River virus strain HV G0090001 nucleocapsid protein gene, partial cds"
251,DQ090889.1,"Blue River virus strain HV G0090001 glycoprotein precursor, gene, partial cds"
252,DQ090890.1,"Blue River virus strain HV G0090028 nucleocapsid protein gene, partial cds"
253,DQ090891.1,"Blue River virus strain HV G0090028 glycoprotein precursor, gene, partial cds"
270,U54582.1,"Sin Nombre hantavirus strain PM-Tx-326 nucleocapsid protein (N) gene, partial cds"
271,U54583.1,"Sin Nombre hantavirus strain PL-Tx-322 nucleocapsid protein (N) gene, partial cds"
272,AF030551.1,"Blue River virus strain Indiana M genome segment glycoprotein precursor, gene, complete cds"
273,AF030552.1,"Blue River virus strain Oklahoma M genome segment glycoprotein precursor, gene, complete cds"
274,U12136.1,"Four Corners hantavirus PMNK-7 nucleocapsid protein gene, partial cds"
275,U47135.1,"Pulmonary syndrome hantavirus H-NY1 nucleocapsin protein gene, complete cds"
276,U36801.1,"New York hantavirus Rhode Island-1 envelope glycoprotein precursor gene, complete cds"
277,U36802.1,"New York hantavirus New York-1 envelope glycoprotein precursor gene, complete cds"
278,U36803.1,"New York hantavirus New York-2 envelope glycoprotein precursor gene, complete cds"
279,U36804.1,"Sin Nombre hantavirus H-ID-1 envelope glycoprotein G1 gene, partial cds"
280,U36805.1,"Sin Nombre hantavirus H-NV-1 envelope glycoprotein G1 gene, partial cds"
281,U36806.1,"Sin Nombre hantavirus H-AB-255 envelope glycoprotein G1 gene, partial cds"
282,U36807.1,"Sin Nombre hantavirus PM-MT-1 envelope glycoprotein G1 gene, partial cds"
283,U36808.1,"Sin Nombre hantavirus PM-NM-28 envelope glycoprotein G1 gene, partial cds"
284,U36809.1,"Sin Nombre hantavirus PL-NM-4 envelope glycoprotein G1 gene, partial cds"
285,U36810.1,"Sin Nombre hantavirus PM-AZ-55 envelope glycoprotein G1 gene, partial cds"
286,U36811.1,"Sin Nombre hantavirus PT-AZ-43 envelope glycoprotein G1 gene, partial cds"
287,U36812.1,"Sin Nombre hantavirus PL-NM-53 envelope glycoprotein G1 gene, partial cds"
288,U36813.1,"Sin Nombre hantavirus H-CO-1 envelope glycoprotein G1 gene, partial cds"
289,U36814.1,"Sin Nombre hantavirus PM-CA-S1 envelope glycoprotein G1 gene, partial cds"
290,U36815.1,"Sin Nombre hantavirus PM-KS-45 envelope glycoprotein G1 gene, partial cds"
291,U36816.1,"Sin Nombre hantavirus PM-BC-147 envelope glycoprotein G1 gene, partial cds"
292,U36817.1,"Sin Nombre hantavirus PM-WA-3 envelope glycoprotein G1 gene, partial cds"
293,U36818.1,"Sin Nombre hantavirus PM-BC-530 envelope glycoprotein G1 gene, partial cds"
294,U36819.1,"Sin Nombre hantavirus PC-CA-SD-20 envelope glycoprotein G1 gene, partial cds"
295,U36820.1,"Sin Nombre hantavirus PM-CA-Ch1 envelope glycoprotein G1 gene, partial cds"
296,U36821.1,"Sin Nombre hantavirus PM-CA-Ch2 envelope glycoprotein G1 gene, partial cds"
297,U17102.1,"Four Corners Hantavirus PL-NM-4 nucleocapsid protein gene, partial cds"
298,U17103.1,"Four Corners Hantavirus PM-MT-1 nucleocapsid protein gene, partial cds"
299,U09308.1,"Four Corners Hantavirus AZ-L nucleocapsid protein gene, partial cds"
300,L37901.1,"Sin Nombre virus (NM H10) RNA L segment encoding RNA polymerase (L protein), complete cds"
301,L37902.1,"Sin Nombre virus (NM R11) RNA L segment encoding RNA polymerase (L protein), complete cds"
302,L37903.1,"Sin Nombre virus (NM R11) RNA M segment encoding surface glycoproteins (G1 and G2 proteins), complete cds"
303,L37904.1,"Sin Nombre virus (NM R11) RNA S segment encoding nucleocapsid protein (N protein), complete cds"
304,U09486.1,"Four Corners hantavirus nucleocapsid protein mRNA, partial cds"

In [95]:
is_nan_segment = sin_nombre['Segment'].isna()

In [96]:
sin_nombre.loc[
    is_nan_segment & sin_nombre['GenBank_Title'].str.contains('nucleocapsid|S RNA segment|S segment|nucleocapsin', case=False, na=False),
    'Segment'
] = 'S'

sin_nombre.loc[
    is_nan_segment & sin_nombre['GenBank_Title'].str.contains('glycoprotein|G1 protein gene|G2 protein gene|M segment', case=False, na=False),
    'Segment'
] = 'M'

sin_nombre.loc[
    is_nan_segment & sin_nombre['GenBank_Title'].str.contains('L segment', case=False, na=False),
    'Segment'
] = 'L'

In [97]:
sin_nombre['Segment'].value_counts(dropna=False)

Segment
M    214
S    108
L     44
Name: count, dtype: int64

In [98]:
cols = ['Accession', 'Segment',  'Nuc_Completeness', 'Species']

In [99]:
all_sequences = sin_nombre[cols]
all_sequences.to_csv('../data/processed_sequences/all_sequences/sin_nombre_all.csv')

In [100]:
complete_sequences = all_sequences[all_sequences['Nuc_Completeness'] == 'complete'].copy()
complete_sequences.to_csv('../data/processed_sequences/complete_sequences/sin_nombre_complete.csv')